.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubeadm alpha phase kubelet enable \- Enables or updates dynamic kubelet configuration on node


.SH SYNOPSIS
.PP
\fBkubeadm alpha phase kubelet enable\fP [OPTIONS]


.SH DESCRIPTION
.PP
Enables or updates dynamic kubelet configuration on node. This should be run on nodes. Please note that the kubelet configuration can be passed to kubeadm as a value into the master configuration file.

.PP
Alpha Disclaimer: this command is currently alpha.


.SH OPTIONS
.PP
\fB\-\-config\fP=""
    Path to kubeadm config file (WARNING: Usage of a configuration file is experimental)

.PP
\fB\-\-node\-name\fP=""
    Name of the node that should enable the dynamic kubelet configuration


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file containing Azure container registry configuration information.

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=5s
    Maximum number of seconds between log flushes

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH EXAMPLE
.PP
.RS

.nf
  # Enables dynamic kubelet configuration on node.
  kubeadm alpha phase kubelet enable

.fi
.RE


.SH SEE ALSO
.PP
\fBkubeadm\-alpha\-phase\-kubelet(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
