.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubeadm alpha phase kubelet config upload \- Uploads kubelet configuration to a ConfigMap based on a kubeadm InitConfiguration file.


.SH SYNOPSIS
.PP
\fBkubeadm alpha phase kubelet config upload\fP [OPTIONS]


.SH DESCRIPTION
.PP
Uploads kubelet configuration extracted from the kubeadm InitConfiguration object to a ConfigMap of the form kubelet\-config\-1.X in the cluster, where X is the minor version of the current (API Server) Kubernetes version.

.PP
Alpha Disclaimer: this command is currently alpha.


.SH OPTIONS
.PP
\fB\-\-config\fP=""
    Path to kubeadm config file (WARNING: Usage of a configuration file is experimental)

.PP
\fB\-\-kubeconfig\fP="/etc/kubernetes/admin.conf"
    The KubeConfig file to use when talking to the cluster


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file containing Azure container registry configuration information.

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-log\-flush\-frequency\fP=5s
    Maximum number of seconds between log flushes

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH EXAMPLE
.PP
.RS

.nf
  # Uploads the kubelet configuration from the kubeadm Config file to a ConfigMap in the cluster.
  kubeadm alpha phase kubelet config upload \-\-config kubeadm.yaml

.fi
.RE


.SH SEE ALSO
.PP
\fBkubeadm\-alpha\-phase\-kubelet\-config(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
