.TH "KUBERNETES" "1" " kubernetes User Manuals" "Eric Paris" "Jan 2015"  ""


.SH NAME
.PP
kubeadm config print\-default \- Print the default values for a kubeadm configuration object.


.SH SYNOPSIS
.PP
\fBkubeadm config print\-default\fP [OPTIONS]


.SH DESCRIPTION
.PP
This command prints the default InitConfiguration object that is used for 'kubeadm init' and 'kubeadm upgrade',
and the default NodeConfiguration object that is used for 'kubeadm join'.

.PP
Note that sensitive values like the Bootstrap Token fields are replaced with silly values like {"abcdef.0123456789abcdef" "" "nil" <nil> [] []} in order to pass validation but
not perform the real computation for creating a token.


.SH OPTIONS
.PP
\fB\-\-api\-objects\fP=[]
    A comma\-separated list for API objects to print the default values for. Available values: [InitConfiguration MasterConfiguration NodeConfiguration]. This flag unset means 'print all known objects'


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-azure\-container\-registry\-config\fP=""
    Path to the file containing Azure container registry configuration information.

.PP
\fB\-\-google\-json\-key\fP=""
    The Google Cloud Platform Service Account JSON Key to use for authentication.

.PP
\fB\-\-kubeconfig\fP="/etc/kubernetes/admin.conf"
    The KubeConfig file to use when talking to the cluster.

.PP
\fB\-\-log\-flush\-frequency\fP=5s
    Maximum number of seconds between log flushes

.PP
\fB\-\-version\fP=false
    Print version information and quit


.SH SEE ALSO
.PP
\fBkubeadm\-config(1)\fP,


.SH HISTORY
.PP
January 2015, Originally compiled by Eric Paris (eparis at redhat dot com) based on the kubernetes source material, but hopefully they have been automatically generated since!
